# Generated by Django 5.2.17 on 2026-08-21 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('Photography', 'Photography'), ('Puncture Shop', 'Puncture Shop'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Tutor', 'Tutor'), ('Tailor', 'Tailor'), ('Beautician', 'Beautician'), ('Mechanic', 'Mechanic'), ('Mobile Repair', 'Mobile Repair'), ('Cleaning', 'Cleaning'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('working_hours', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
