# Generated by Django 5.2.17 on 2026-09-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
