# Generated by Django 5.2.17 on 2026-09-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceprovider_latitude_serviceprovider_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='category',
            field=models.CharField(choices=[('Photography', 'Photography'), ('Videography', 'Videography'), ('Puncture Shop', 'Puncture Shop'), ('Mechanic', 'Mechanic'), ('Car Wash', 'Car Wash'), ('Bike Service', 'Bike Service'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Carpenter', 'Carpenter'), ('Painter', 'Painter'), ('AC Repair', 'AC Repair'), ('Refrigerator Repair', 'Refrigerator Repair'), ('Washing Machine Repair', 'Washing Machine Repair'), ('Water Purifier Service', 'Water Purifier Service'), ('CCTV Installation', 'CCTV Installation'), ('Solar Panel Service', 'Solar Panel Service'), ('Pest Control', 'Pest Control'), ('Cleaning', 'Cleaning'), ('Mobile Repair', 'Mobile Repair'), ('Laptop Repair', 'Laptop Repair'), ('Computer Repair', 'Computer Repair'), ('Tailor', 'Tailor'), ('Beautician', 'Beautician'), ('Makeup Artist', 'Makeup Artist'), ('Mehendi Artist', 'Mehendi Artist'), ('Tutor', 'Tutor'), ('Driving School', 'Driving School'), ('Fitness Trainer', 'Fitness Trainer'), ('Yoga Trainer', 'Yoga Trainer'), ('Cook', 'Cook'), ('Laundry', 'Laundry'), ('Catering', 'Catering'), ('Event Decoration', 'Event Decoration'), ('Interior Design', 'Interior Design'), ('Taxi Service', 'Taxi Service'), ('Packers and Movers', 'Packers and Movers'), ('Other', 'Other')], max_length=50),
        ),
    ]
